RazorProject/Models/OpslagViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RazorProject.Models
{
    public class OpslagViewModel
    {
        [Display(Name = "Van wedde: ")]
        [Required(ErrorMessage = "Van wedde is een verplicht veld")]
        public decimal? VanWedde { get; set; }

        [Display(Name = "Tot wedde: ")]
        [Required(ErrorMessage = "Van wedde is een verplicht veld")]
        public decimal? TotWedde { get; set; }

        [Display(Name = "Percentage: ")]
        [Range(0,100,ErrorMessage = "De minimum en maximumwaarden voor percentage zijn: {1} en {2}")]
        public decimal Percentage { get; set; }
    }
}

RazorProject/Models/Persoon.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RazorProject.Models
{
    public class Persoon
    {
        public int Id { get; set; }
        public string Voornaam { get; set; }
        public string Familienaam { get; set; }
        public int Score { get; set; }

        [DisplayFormat(DataFormatString = "{0:€ #,##0.00}")]
        public decimal Wedde { get; set; }

        [DataType(DataType.Password)]
        public string Paswoord { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode=true)]
        public DateTime Geboren { get; set; }
        public bool Gehuwd { get; set; }
        public string Opmerkingen { get; set; }
        public Geslacht Geslacht { get; set; }    
    }
}

RazorProject/Models/VanTotWeddeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RazorProject.Models
{
    public class VanTotWeddeViewModel : IValidatableObject
    {
        [Display(Name = "Van wedde")]
        [Required(ErrorMessage = "Van wedde is verplicht")]
        public decimal? VanWedde { get; set; }

        [Display(Name = "Tot wedde")]
        [Required(ErrorMessage = "Tot wedde is verplicht")]
        public decimal? TotWedde { get; set; }

        public List<Persoon> Personen { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            var validationResults = new List<ValidationResult>();
            if (VanWedde > TotWedde)
            {
                validationResults.Add(new ValidationResult("VanWedde is groter dan TotWedde"));
            }

            return validationResults;
        }
    }
}

RazorProject/Controllers/PersoonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RazorProject.Models;
using RazorProject.Services;

namespace RazorProject.Controllers
{
    public class PersoonController : Controller
    {
        private PersoonService _persoonService;

        public PersoonController(PersoonService persoonService)
        {
            _persoonService = persoonService;
        }
        public IActionResult Index()
        {
            return View(_persoonService.FindAll());
        }

        [HttpGet]
        public IActionResult VerwijderForm(int id)
        {
            return View(_persoonService.FindById(id));
        }

        [HttpPost]
        public IActionResult Verwijderen(int id)
        {
            _persoonService.Delete(id);
            return RedirectToAction("Index");
        }
        
        public IActionResult Opslag()
        {
            OpslagViewModel opslagViewModel = new OpslagViewModel();
            opslagViewModel.Percentage = 10;
            return View(opslagViewModel);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Opslag(OpslagViewModel opslagViewModel)
        {
            if (this.ModelState.IsValid)
            {
                _persoonService.Opslag(opslagViewModel.VanWedde.Value, opslagViewModel.TotWedde.Value, opslagViewModel.Percentage);
                return RedirectToAction("Index");
            } else
            {
                return View(opslagViewModel);
            }
            
        }

        [HttpGet]
        public IActionResult VanTotWedde()
        {
            var form = new VanTotWeddeViewModel();
            return View(form);
        }

        [HttpGet]
        public IActionResult VanTotWeddeResultaat(VanTotWeddeViewModel form)
        {
            if (this.ModelState.IsValid)
            {
                form.Personen = _persoonService.VanTotWedde(form.VanWedde.Value, form.TotWedde.Value);
            }

            return View("VanTotWedde", form);
        }

        [HttpGet]
        public IActionResult Toevoegen()
        {
            var persoon = new Persoon();
            persoon.Score = 1;
            return View(persoon);
        }

        [HttpPost]
        public IActionResult Toevoegen(Persoon p)
        {
            if (this.ModelState.IsValid)
            {
                _persoonService.Add(p);
                return RedirectToAction("Index");
            } else
            {
                return View(p);
            }
        }
    }
}

RazorProject/Views/Persoon/Index.cshtml
@model IEnumerable<Persoon>
@{
    ViewData["Title"] = "Index";
}

<h1>Personen</h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(m => m.Id)</th>
            <th>@Html.DisplayNameFor(m => m.Voornaam)</th>
            <th>@Html.DisplayNameFor(m => m.Familienaam)</th>
            <th>@Html.DisplayNameFor(m => m.Score)</th>
            <th>@Html.DisplayNameFor(m => m.Wedde)</th>
            <th>@Html.DisplayNameFor(m => m.Paswoord)</th>
            <th>@Html.DisplayNameFor(m => m.Geboren)</th>
            <th>@Html.DisplayNameFor(m => m.Gehuwd)</th>
            <th>@Html.DisplayNameFor(m => m.Opmerkingen)</th>
            <th>@Html.DisplayNameFor(m => m.Geslacht)</th>
            <th>Verwijderen</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var persoon in Model)
        {
        <tr>
            <td>@Html.DisplayFor(m => persoon.Id)</td>
            <td>@Html.DisplayFor(m => persoon.Voornaam)</td>
            <td>@Html.DisplayFor(m => persoon.Familienaam)</td>
            <td>@Html.DisplayFor(m => persoon.Score)</td>
            <td>@Html.DisplayFor(m => persoon.Wedde)</td>
            <td>@Html.DisplayFor(m => persoon.Paswoord)</td>
            <td>@Html.DisplayFor(m => persoon.Geboren)</td>
            <td>@Html.DisplayFor(m => persoon.Gehuwd)</td>
            <td>@Html.DisplayFor(m => persoon.Opmerkingen)</td>
            <td>@Html.DisplayFor(m => persoon.Geslacht)</td>
            <td>
                <a asp-action="VerwijderForm" asp-controller="Persoon" asp-route-id="@persoon.Id">
                <img src="~/images/delete.png" /></a>
            </td>
        </tr>
        }
    </tbody>
</table>

<a asp-action="Opslag" asp-controller="Persoon" class="btn btn-primary">Opslag</a>
<a asp-action="Toevoegen" asp-controller="Persoon" class="btn btn-primary">Toevoegen</a>

RazorProject/Views/Persoon/Opslag.cshtml
@model OpslagViewModel
@{
    ViewBag.Title = "Opslag";
}

<h2>Opslag</h2>
<form asp-action="Opslag" method="post" asp-antiforgery="true">
    <label asp-for="VanWedde"></label>
    <span asp-validation-for="VanWedde">*</span>
    <input asp-for="VanWedde" />
    <label asp-for="TotWedde"></label>
    <span asp-validation-for="TotWedde">*</span>
    <input asp-for="TotWedde" />
    <label asp-for="Percentage"></label>
    <span asp-validation-for="Percentage">*</span>
    <input asp-for="Percentage" />
    <input type="submit" value="Weddeverhoging doorvoeren" />
</form>
<div asp-validation-summary="All">Er zijn validatiefouten</div>

RazorProject/Views/Persoon/Toevoegen.cshtml
@model Persoon
@{
    ViewData["Title"] = "Toevoegen";
}

<h1>Toevoegen</h1>

<form asp-action="Toevoegen" method="post">
    <label asp-for="Voornaam"></label>
    <input asp-for="Voornaam" />
    <label asp-for="Familienaam"></label>
    <input asp-for="Familienaam" />
    <label asp-for="Score"></label>
    <input asp-for="Score" />
    <label asp-for="Wedde"></label>
    <input asp-for="Wedde" />
    <label asp-for="Paswoord"></label>
    <input asp-for="Paswoord" type="password"/>
    <label asp-for="Geboren"></label>
    <input asp-for="Geboren" />
    <label asp-for="Gehuwd"></label>
    <input asp-for="Gehuwd" />
    <label asp-for="Opmerkingen"></label>
    <textarea asp-for="Opmerkingen"></textarea>
    @*<label asp-for="Geslacht"></label>
    <select asp-for="Geslacht" asp-items="@new SelectList(Enum.GetNames(typeof(Geslacht)))"></select>*@
    @Html.LabelFor(m => m.Geslacht)
    @Html.EditorFor(m => m.Geslacht)
    <input type="submit" value="Toevoegen" />
    <div asp-validation-summary="All"></div>
</form>

RazorProject/Views/Persoon/VanTotWedde.cshtml
@model VanTotWeddeViewModel
@{
    ViewData["Title"] = "VanTotWedde";
}

<h2>Weddes tussen twee grenzen</h2>

<form asp-action="VanTotWeddeResultaat" method="get">
    <label asp-for="VanWedde"></label>
    <span asp-validation-for="VanWedde"></span>
    <input asp-for="VanWedde" />
    <label asp-for="TotWedde"></label>
    <span asp-validation-for="TotWedde"></span>
    <input asp-for="TotWedde" />
    <input type="submit" value="Zoeken"/>
    <div asp-validation-summary="All"></div>
</form>

@if (Model.Personen != null)
{
    <ul>
        @foreach (var persoon in Model.Personen)
        {
            <li>@persoon.Voornaam @persoon.Familienaam @persoon.Wedde</li>
        }
    </ul>
}

RazorProject/Views/Persoon/VerwijderForm.cshtml
@model Persoon
@{
    ViewBag.Title = Model.Voornaam + " " + Model.Familienaam + " verwijderen?";
}

<h2>@Model.Voornaam @Model.Familienaam verwijderen?</h2>
<form method="post" asp-action="Verwijderen" asp-route-id="@Model.Id">
    <input type="submit" value="Verwijderen" />
</form>